### ISSUE TITLE
rqt_dashboard/scripts/rqt_dashboard missing?

### ISSUE THREAD

**Issue by hsu** [Georacer/last_letter#50]
catkin_make install yields:

~~~
CMake Error at last_letter/rqt_dashboard/cmake_install.cmake:68 (FILE):
  file INSTALL cannot find
  "/home/hsu/projects/catkin_last_letter/src/last_letter/rqt_dashboard/scripts/rqt_dashboard".
Call Stack (most recent call first):
  cmake_install.cmake:129 (INCLUDE)


make: *** [install] Error 1
~~~

is this expected?  thanks.

**Comment by Georacer** [comment]
Why did you run a `catkin_make install` instead of a simple `catkin_make`? I don't believe I have written that this command should be run, in the documentation.
There is no install file in the rqt_dashboard package, hence the error.

**Comment by Georacer** [comment]
Was the problem resolved by running `catkin_make`?

**Comment by Georacer** [comment]
The OP didn't provide more information on the error. This is closed, on the assumption that it is solved.
